CREATE TABLE "users" (
                         "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                         "email" text UNIQUE NOT NULL,
                         "hashed_password" text NOT NULL,
                         "created_at" timestamp NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_email ON users (email);

CREATE TABLE "data" (
                        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                        "owner_id" integer NOT NULL,
                        "type" text,
                        "data" bytea NOT NULL,
                        "metadata" bytea,
                        "created_at" timestamp NOT NULL,
                        "deleted" bool DEFAULT false,
                        "deleted_at" timestamp
);
CREATE INDEX IF NOT EXISTS idx_owner_id ON data (owner_id);

COMMENT ON COLUMN "data"."type" IS 'LP_PAIR|TEXT|BINARY|BANK_CARD';

ALTER TABLE "data" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");
