CREATE TABLE "users" (
                         "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                         "email" text UNIQUE NOT NULL,
                         "hashed_password" text NOT NULL,
                         "created_at" timestamp NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_email ON users (email);

CREATE TABLE IF NOT EXISTS "passwords" (
                        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                        "owner_id" integer NOT NULL,
                        "login" text NOT NULL,
                        "password" text NOT NULL,
                        "metadata" text,
                        "created_at" timestamp NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_owner_id ON passwords (owner_id);
ALTER TABLE "passwords" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");

CREATE TABLE IF NOT EXISTS "cards" (
                             "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                             "owner_id" integer NOT NULL,
                             "number" text NOT NULL,
                             "cvc" text NOT NULL,
                             "owner" text NOT NULL,
                             "date" text NOT NULL,
                             "metadata" text,
                             "created_at" timestamp NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_owner_id ON cards (owner_id);
ALTER TABLE "cards" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");

CREATE TABLE IF NOT EXISTS "texts" (
                         "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                         "owner_id" integer NOT NULL,
                         "text" text NOT NULL,
                         "metadata" text,
                         "created_at" timestamp NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_owner_id ON texts (owner_id);
ALTER TABLE "texts" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");

CREATE TABLE IF NOT EXISTS "files" (
                           "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                           "owner_id" integer NOT NULL,
                           "filename" text NOT NULL,
                           "uploaded" boolean default false,
                           "metadata" text,
                           "created_at" timestamp NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_owner_id ON files (owner_id);
ALTER TABLE "files" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");